name: Push
on: [ push ]
jobs:
  Create-Release-Tag:
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.ref , 'refs/heads/release') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          TAG_CONTEXT: 'branch'
          INITIAL_VERSION: ${{ github.ref }}
  Deploy-Snapshot-Version:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith( github.ref , 'refs/heads/release') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}