on: push
jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    if: {{ startsWith($GITHUB_REF, 'refs/heads/release-') }}
    steps:
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: $GITHUB_REF
  deploy-snapshot-version:
    runs-on: ubuntu-latest
    if: {{ !startsWith($GITHUB_REF, 'refs/heads/release-') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B deploy --file pom.xml