name: Push
on: [ push ]
jobs:
  Deploy-Release-Version:
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.ref , 'refs/heads/release') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Calculate initial version
        uses: actions/github-script@v5.0.0
        id: initial-release
        with:
          script: return context.ref.substring(context.ref.indexOf("release/") + 8) + ".0"
          result-encoding: string
      - name: Bump version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: 'release.*'
          WITH_V: false
          TAG_CONTEXT: 'branch'
          INITIAL_VERSION: ${{ steps.initial-release.outputs.result }}
          DEFAULT_BUMP: 'patch'
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Deploy
        run: mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ 'refs/tags/' + steps.github-tag-action.outputs.new_tag }}
  Deploy-Snapshot-Version:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith( github.ref , 'refs/heads/release') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Deploy
        run: mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}